'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { api } from '@/lib/api/client'
import { ArrowUpRight, Package, ShoppingBag, TrendingUp, Users } from 'lucide-react'
import { DashboardShell } from '@/components/dashboard/DashboardShell'
import { formatPrice } from '@/lib/data'
const defaultStats = { totalProducts: 0, todayOrders: 0, todayRevenue: 0, totalCustomers: 0 }
const stats = (data: typeof defaultStats) => [{ label: 'Total products', value: String(data.totalProducts), note: 'Live from API', icon: Package }, { label: "Today's orders", value: String(data.todayOrders), note: 'Live from API', icon: ShoppingBag }, { label: "Today's revenue", value: formatPrice(data.todayRevenue), note: 'Live from API', icon: TrendingUp }, { label: 'Total customers', value: String(data.totalCustomers), note: 'Live from API', icon: Users }]
export default function DashboardPage() { const [data, setData] = useState(defaultStats); useEffect(() => { api.get<any>('/admin/dashboard/stats').then((response) => setData({ ...defaultStats, ...(response?.data || response) })).catch(() => {}) }, []); return <DashboardShell title="Dashboard" description="Manage your restaurant products and orders."><section className="dashboard-stats">{stats(data).map(({ label, value, note, icon: Icon }) => <article key={label}><div className="stat-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><section className="dashboard-panels"><article className="dashboard-panel dashboard-welcome"><span className="dashboard-eyebrow">Today at Bilal Broast</span><h2>Keep the kitchen<br /><i>moving.</i></h2><p>Review new orders, keep your menu fresh, and make every delivery count.</p><Link href="/dashboard/products" className="button button-primary">Manage products <ArrowUpRight size={16} /></Link></article><article className="dashboard-panel"><div className="panel-heading"><div><span className="dashboard-eyebrow">Quick actions</span><h2>What needs attention</h2></div></div><Link className="quick-link" href="/dashboard/products/new"><Package size={18} /><span><strong>Add a new product</strong><small>Keep the menu exciting</small></span><ArrowUpRight size={16} /></Link><Link className="quick-link" href="/dashboard/orders"><ShoppingBag size={18} /><span><strong>Review today&apos;s orders</strong><small>42 orders in progress</small></span><ArrowUpRight size={16} /></Link></article></section></DashboardShell> }
